/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ArmandNokbak.ForeignLanguageTerritory;

import foreign.language.territory.management.kit.ForeignLanguageTerritoryManagementKit;
import java.awt.Color;
import java.awt.Frame;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.net.InetAddress;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author anokbakn
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        logInPanel = new javax.swing.JPanel();
        userNameLbl = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JLabel();
        pwdField = new javax.swing.JPasswordField();
        logOnBtn = new javax.swing.JButton();
        errorLbl = new javax.swing.JLabel();
        forgotPasswordLbl = new javax.swing.JLabel();
        changePasswordLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Foreign Language Territory Management Kit");
        setBackground(new java.awt.Color(51, 51, 51));
        setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        setIconImage(new ImageIcon(getClass().getResource("SearchIcon.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logInPanel.setBackground(new java.awt.Color(255, 255, 255));
        logInPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true)));
        logInPanel.setEnabled(false);
        logInPanel.setMinimumSize(new java.awt.Dimension(400, 400));

        userNameLbl.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        userNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        userNameLbl.setText("Username : ");

        userNameField.setBackground(new java.awt.Color(204, 204, 204));
        userNameField.setFont(userNameLbl.getFont());

        passwordLbl.setFont(userNameLbl.getFont());
        passwordLbl.setForeground(userNameLbl.getForeground());
        passwordLbl.setText("Password : ");

        pwdField.setBackground(userNameField.getBackground());
        pwdField.setFont(userNameField.getFont());
        pwdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdFieldActionPerformed(evt);
            }
        });

        logOnBtn.setFont(passwordLbl.getFont());
        logOnBtn.setForeground(passwordLbl.getForeground());
        logOnBtn.setText("Log on");
        logOnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOnBtnActionPerformed(evt);
            }
        });

        errorLbl.setFont(passwordLbl.getFont());
        errorLbl.setForeground(new java.awt.Color(255, 0, 0));

        forgotPasswordLbl.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        forgotPasswordLbl.setForeground(passwordLbl.getForeground());
        forgotPasswordLbl.setText("Forgot your password ?");
        forgotPasswordLbl.setToolTipText("forgot password");
        forgotPasswordLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgotPasswordLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotPasswordLblMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                forgotPasswordLblMouseReleased(evt);
            }
        });

        changePasswordLbl.setFont(forgotPasswordLbl.getFont());
        changePasswordLbl.setForeground(forgotPasswordLbl.getForeground());
        changePasswordLbl.setText("Change Your password");
        changePasswordLbl.setToolTipText("Change password");
        changePasswordLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changePasswordLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changePasswordLblMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                changePasswordLblMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout logInPanelLayout = new javax.swing.GroupLayout(logInPanel);
        logInPanel.setLayout(logInPanelLayout);
        logInPanelLayout.setHorizontalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInPanelLayout.createSequentialGroup()
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logOnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(logInPanelLayout.createSequentialGroup()
                                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userNameLbl)
                                    .addComponent(passwordLbl)
                                    .addComponent(forgotPasswordLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(userNameField)
                                        .addComponent(pwdField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                                    .addComponent(changePasswordLbl, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(50, 50, 50))
        );
        logInPanelLayout.setVerticalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(errorLbl)
                .addGap(53, 53, 53)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLbl)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLbl)
                    .addComponent(pwdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(logOnBtn)
                .addGap(18, 18, 18)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forgotPasswordLbl)
                    .addComponent(changePasswordLbl))
                .addGap(40, 40, 40))
        );

        phoneLbl.setFont(new java.awt.Font("Trebuchet MS", 2, 8)); // NOI18N
        phoneLbl.setForeground(forgotPasswordLbl.getForeground());
        phoneLbl.setText("+1 (202) 578 - 9881");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logInPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logInPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneLbl)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOnBtnActionPerformed
        //if credentials correct
        if(userNameField.getText().equalsIgnoreCase(ForeignLanguageTerritoryManagementKit.user.getUserName()) && 
                pwdField.getText().equals(ForeignLanguageTerritoryManagementKit.user.getPwd()))
        {
            Home home = new Home();
            home.setExtendedState(JFrame.MAXIMIZED_BOTH);
            home.setVisible(true);
            this.hide();
        }// end of if credentials correct
        else //if credentials incorrect
        {
            errorLbl.setText("Username or password incorrect.");
            pwdField.setText("");
        }//end of if credentials incorrect
    }//GEN-LAST:event_logOnBtnActionPerformed

    private void pwdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdFieldActionPerformed
        logOnBtn.doClick();
    }//GEN-LAST:event_pwdFieldActionPerformed

    private void forgotPasswordLblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordLblMouseReleased
        

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.port", "465");

        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication("ardeondia@gmail.com", "Johndoe57");
                    }
                }
        );

        try {

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(ForeignLanguageTerritoryManagementKit.user.getEmail(), ForeignLanguageTerritoryManagementKit.user.getUserName()
                    + " from " + ForeignLanguageTerritoryManagementKit.user.getCongregation()));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(ForeignLanguageTerritoryManagementKit.user.getEmail()));
            message.setSubject("ASP Finder ... Your password and user name.");
            message.setText("Hello "+ForeignLanguageTerritoryManagementKit.user.getUserName()+",\n"
                    +"Your user name is '"+ForeignLanguageTerritoryManagementKit.user.getUserName()
            +"', and your password is '"+ForeignLanguageTerritoryManagementKit.user.getPwd()+"'.\n"
            +"\nThanks for using All Sorts of People Finder.\n\nYour developer.");
            Transport.send(message);
            JOptionPane.showMessageDialog(null, "An email was just sent to you with your credentials. Thank you.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An internet connection was not detected.\n"
                    + "Please, try again when connected to the internet!");

        }
        
       
    }//GEN-LAST:event_forgotPasswordLblMouseReleased

    private void changePasswordLblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordLblMouseReleased
        //Opening the ChangePasswordFrame
        ChangePasswordFrame changePwd = new ChangePasswordFrame();
        changePwd.setVisible(true);
        
        
    }//GEN-LAST:event_changePasswordLblMouseReleased

    private void forgotPasswordLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordLblMouseEntered
        forgotPasswordLbl.setForeground(Color.RED);
    }//GEN-LAST:event_forgotPasswordLblMouseEntered

    private void forgotPasswordLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordLblMouseExited
        forgotPasswordLbl.setForeground(passwordLbl.getForeground());
    }//GEN-LAST:event_forgotPasswordLblMouseExited

    private void changePasswordLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordLblMouseExited
        changePasswordLbl.setForeground(passwordLbl.getForeground());
    }//GEN-LAST:event_changePasswordLblMouseExited

    private void changePasswordLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordLblMouseEntered
        changePasswordLbl.setForeground(Color.RED);
    }//GEN-LAST:event_changePasswordLblMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                               
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changePasswordLbl;
    private javax.swing.JLabel errorLbl;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel forgotPasswordLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel logInPanel;
    private javax.swing.JButton logOnBtn;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JPasswordField pwdField;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLbl;
    // End of variables declaration//GEN-END:variables
}
